version: "3.8"

services:
  api:
    image: ghcr.io/madebaruna/paimon-moe-api:latest
    init: true
    restart: always
    ports:
      - "22000:3001"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      XXHASH_SEED: ${XXHASH_SEED}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      REDIS_URL: ${REDIS_URL}
      TALLY_QUEUE_CONCURRENCY: ${TALLY_QUEUE_CONCURRENCY}
      PLAUSIBLE_URL: ${PLAUSIBLE_URL}
      PLAUSIBLE_TOKEN: ${PLAUSIBLE_TOKEN}
      HEADER_SECRET: ${HEADER_SECRET}
      PROXY_LOCATION: ${PROXY_LOCATION}
    volumes:
      - /home/baruna/server/service_account:/service_account
      - /home/baruna/server/proxies:/proxies
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  # postgres:
  #   image: postgres:13.9
  #   restart: always
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   command: 
  #     - "postgres"
  #     - "-c"
  #     - "shared_buffers=12GB"
  #     - "-c"
  #     - "effective_cache_size=36GB" 
  #     - "-c"
  #     - "maintenance_work_mem=2GB"
  #     - "-c"
  #     - "wal_buffers=16MB"
  #     - "-c"
  #     - "effective_io_concurrency=200"
  #     - "-c"
  #     - "work_mem=15728kB"
  #     - "-c"
  #     - "min_wal_size=1GB"
  #     - "-c"
  #     - "max_wal_size=4GB"
  #     - "-c"
  #     - "max_worker_processes=8"
  #     - "-c"
  #     - "max_parallel_workers_per_gather=4"
  #     - "-c"
  #     - "max_parallel_workers=8"
  #     - "-c"
  #     - "max_parallel_maintenance_workers=4"
  #   environment:
  #     POSTGRES_DB: ${DB_DATABASE}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}

  # redis:
  #   image: redis:6.2.4-alpine
  #   restart: always
  #   volumes:
  #     - redis_data:/data

volumes:
  db_data:
  redis_data:
